name: MacOS
on: 
  # Trigger workflow on pushes
  push:
    paths:
      - '*.pro'
      - '**'
      - '.github/workflows/macos.yml'
  # Trigger workflow on pull requests
  pull_request:
    paths:
      - '*.pro'
      - '**'
      - '.github/workflows/macos.yml' 
  # Enables the manual "Run workflow" trigger button in GitHub Actions
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - qt_ver: 5.15.2
            qt_arch: clang_64
        
    env:
      targetName: OCAuxiliaryTools
      VERSION: Mac
      orgName: OCAT
      
    steps:
      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          cached: 'false'

      # Check out repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # Build via Make
      - name: macos-build
        id: build
        run: |
          qmake
          make

      # Package compiled binary
      - name: package
        id: package      
        env:
          archiveName: ${{ env.orgName }}-${{ env.VERSION }}
        run: |
          # Copy dependencies
          cp -r Database bin/release/${targetName}.app/Contents/MacOS/Database
          chmod +x bin/release/${targetName}.app/Contents/MacOS/Database/mac/macserial
          chmod +x bin/release/${targetName}.app/Contents/MacOS/Database/mac/ocvalidate
          chmod +x bin/release/${targetName}.app/Contents/MacOS/Database/mac/ocpasswordgen
          
          chmod +x bin/release/${targetName}.app/Contents/MacOS/Database/mac/CreateVault/create_vault.sh
          chmod +x bin/release/${targetName}.app/Contents/MacOS/Database/mac/CreateVault/RsaTool
          chmod +x bin/release/${targetName}.app/Contents/MacOS/Database/mac/CreateVault/sign.command
          
          cp -f Info.plist bin/release/${targetName}.app/Contents/Info.plist
          
          cp -f Database/mac/aria2c bin/release/${targetName}.app/Contents/MacOS/aria2c
          chmod +x bin/release/${targetName}.app/Contents/MacOS/aria2c
          rm bin/release/${targetName}.app/Contents/MacOS/Database/mac/aria2c
          
          cp -R -p -f bin/release/${targetName}.app ${targetName}.app
          macdeployqt ${targetName}.app -qmldir=. -verbose=1 -dmg
          cp ${targetName}.dmg bin/release/${archiveName}.dmg
          
          echo "packageName=${archiveName}" >> $GITHUB_OUTPUT
          
      # Upload compiled dmg file as a workflow artifact          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.packageName }}
          path: bin/release/${{ steps.package.outputs.packageName }}.dmg
          
      # Optional: Upload to GitHub Releases if triggered by a Git tag
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/release/${{ steps.package.outputs.packageName }}.dmg
          asset_name: ${{ steps.package.outputs.packageName }}.dmg
          tag: ${{ github.ref }}
          overwrite: true
