name: Windows
on: 
  # Trigger workflow on pushes
  push:
    paths:
      - '*.pro'
      - '**'
      - '.github/workflows/windows.yml'
  # Trigger workflow on pull requests
  pull_request:
    paths:
      - '*.pro'
      - '**'
      - '.github/workflows/windows.yml' 
  # Enables the manual "Run workflow" trigger button in GitHub Actions
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - qt_ver: 5.15.2          
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64          
          
    env:
      targetName: OCAuxiliaryTools.exe
      VERSION: Win64
      orgName: OCAT
      
    steps:
      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          cached: 'false'

      # Check out repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # Dynamically get VS path
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

      # Build via MSVC
      - name: msvc-build
        id: build
        shell: cmd
        run: |
          qmake
          nmake
          echo winSdkDir=%WindowsSdkDir% >> %GITHUB_ENV%
          echo winSdkVer=%WindowsSdkVersion% >> %GITHUB_ENV%
          echo vcToolsInstallDir=%VCToolsInstallDir% >> %GITHUB_ENV%
          echo vcToolsRedistDir=%VCToolsRedistDir% >> %GITHUB_ENV%

      # Package compiled binary
      - name: package
        id: package      
        env:
          archiveName: ${{ env.orgName }}-${{ env.VERSION }}
          msvcArch: ${{ matrix.msvc_arch }}          
        shell: pwsh
        run: |
          & scripts\windows-publish.ps1 ${env:archiveName} ${env:targetName}
          $name = ${env:archiveName}
          echo "packageName=$name" >> $env:GITHUB_OUTPUT
          
      # Upload compiled zip file as a workflow artifact          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.packageName }}
          path: ${{ steps.package.outputs.packageName }}.zip
          
      # Optional: Upload to GitHub Releases if triggered by a Git tag
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.package.outputs.packageName }}.zip
          asset_name: ${{ steps.package.outputs.packageName }}.zip
          tag: ${{ github.ref }}
          overwrite: true
